# Compiler and linker settings
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -g -Iinclude `pkg-config --cflags freetype2`
LDFLAGS = `pkg-config --libs freetype2` -lGL -lGLU -lSDL2 -ldl -lft

# Source files and object files
SRC = src/ball.cpp src/debugger.cpp src/game.cpp src/game_object.cpp src/main.cpp src/text_renderer.cpp src/glad.c
OBJ = $(SRC:.cpp=.o)

# Output binary
TARGET = Pong

# Build directories
BUILD_DIR = build

# Make rules
all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET) $(LDFLAGS)

# Compile .cpp files into .o files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $(BUILD_DIR)/$@

# Clean build
clean:
	rm -rf $(BUILD_DIR) $(TARGET)

# Create build directory if it doesn't exist
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Phony targets
.PHONY: all clean

